//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Алалыкин_Глазки_save
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text.RegularExpressions;

    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public int AgentTypeID { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public int Priority { get; set; }
        public string DirectorName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string AgentTypeTitle { get
            {
                return AgentType.Title;
            }
            set { if (AgentType.ID == AgentTypeID) AgentTypeTitle=AgentType.Title; }
        }
        public int SalesForYear
        {
            get
            {
                int sales = 0;
                DateTime Date = DateTime.Today.Date;
                foreach (ProductSale productSale in ProductSale)
                {
                    TimeSpan differenceWithoutTime = Date - productSale.SaleDate.Date;
                    //if (differenceWithoutTime.TotalDays <= 365)
                        sales += productSale.ProductCount;
                }
                return sales;
            }
        }
        public decimal Sales
        {
            get
            {
                decimal s = 0;
                foreach (ProductSale productSale in ProductSale)
                {
                    s += productSale.Cost;
                }
                return s;
            }
        }
        public string AgentLogo
        {
            get
            {
                if (Logo == "") return "agents/picture.png";
                else return Logo;
            }
        }
        public int Discount
        {
            get
            {
                if (this.Sales >= 500000)
                    return 25;
                if (this.Sales >= 150000)
                    return 20;
                if (this.Sales >= 50000)
                    return 10;
                if (this.Sales >= 10000)
                    return 5;
                return 0;
            }
        }
        public string FontStyle
        {
            get
            {
                if (Discount >= 25) return "LightGreen";
                else return "White";
            }
        }
        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
